#!/bin/bash
# Install the Menegroth server unlock agent on this Mac. Idempotent; re-run after
# editing menegroth-server-unlock.sh to update the installed copy.
#
# All secrets live in 1Password (dedicated vault, service-account read-only
# access). This installer writes two values to disk, both 0600 (FileVault at
# rest): the service-account token, so the agent keeps working across Mac
# reboots without re-running this installer, and a copy of the ntfy topic
# URL, so alerts still go out when 1Password can't be read (a revoked token
# is exactly when you need the alert). The ntfy URL can post to and read
# your notification topic, nothing more.
set -euo pipefail
cd "$(dirname "$0")"

BIN="${HOME}/.local/bin/menegroth-server-unlock"
PLIST_DEST="${HOME}/Library/LaunchAgents/com.menegroth-server.unlock.plist"
TOKEN_FILE="${HOME}/.config/menegroth-server-unlock/op-token"
CONFIG="${HOME}/.config/menegroth-server-unlock/config"
OP_VAULT="Menegroth"

OP="$(command -v op || true)"
[[ -z "$OP" && -x /opt/homebrew/bin/op ]] && OP=/opt/homebrew/bin/op
[[ -z "$OP" && -x /usr/local/bin/op ]] && OP=/usr/local/bin/op
if [[ -z "$OP" ]]; then
  echo "ERROR: 1Password CLI not found — install with: brew install 1password-cli" >&2
  exit 1
fi

echo "==> Installing unlock script to $BIN"
mkdir -p "${HOME}/.local/bin" "${HOME}/.local/state/menegroth-server-unlock" \
  "${HOME}/.config/menegroth-server-unlock"
install -m 0700 menegroth-server-unlock.sh "$BIN"

if [[ ! -f "$TOKEN_FILE" ]]; then
  echo "==> Storing the menegroth-unlock service-account token (0600)"
  if [[ -n "${MENEGROTH_OP_UNLOCK_TOKEN:-}" ]]; then
    OP_TOKEN="$MENEGROTH_OP_UNLOCK_TOKEN"
    echo "    Using \$MENEGROTH_OP_UNLOCK_TOKEN from the environment."
  else
    echo "    This is the READ-ONLY service account scoped to the '$OP_VAULT'"
    echo "    vault only (README seed steps). Paste its token (it will not echo):"
    read -rs OP_TOKEN
    echo
  fi
  umask 177
  printf '%s\n' "$OP_TOKEN" > "$TOKEN_FILE"
  umask 022
  unset OP_TOKEN
fi

# ---- Server address (origin verification, docs/architecture.md D11) -------
# The agent unlocks only a boot node that answers DIRECTLY from the server's
# own public address. Source: `terraform output` (server_ipv4 /
# server_ipv6_network — Hetzner Primary IPs, stable across image rolls) or
# Hetzner console -> Primary IPs. Unset = the agent fails closed (never
# unlocks), which is expected before the first `terraform apply`.
ip_kind() { # ip_kind <value> -> prints 4, 6net, or nothing if invalid
  /usr/bin/python3 - "$1" <<'PY'
import ipaddress
import sys

v = sys.argv[1]
try:
    if "/" in v:
        net = ipaddress.ip_network(v, strict=False)
        print("6net" if net.version == 6 else "")
    else:
        print("4" if ipaddress.ip_address(v).version == 4 else "")
except ValueError:
    pass
PY
}

set_config() { # set_config KEY VALUE — replace or append one line in $CONFIG
  local tmp
  tmp="$(mktemp)" # 0600
  { grep -v "^$1=" "$CONFIG" 2>/dev/null || true; printf '%s=%q\n' "$1" "$2"; } >"$tmp"
  mv "$tmp" "$CONFIG"
}

echo "==> Server address for boot-node origin verification"
v4="${MENEGROTH_SERVER_IPV4:-}"
v6="${MENEGROTH_SERVER_IPV6_NET:-}"
if [[ -z "$v4" && -t 0 ]] && ! grep -q '^SERVER_IPV4=.' "$CONFIG" 2>/dev/null; then
  read -rp "    Server public IPv4 (terraform output server_ipv4; empty = set later): " v4
  [[ -z "$v4" ]] || read -rp "    Server IPv6 network (terraform output server_ipv6_network; empty = none): " v6
fi
if [[ -n "$v4" ]]; then
  [[ "$(ip_kind "$v4")" == 4 ]] || { echo "ERROR: '$v4' is not an IPv4 address" >&2; exit 1; }
  set_config SERVER_IPV4 "$v4"
fi
if [[ -n "$v6" ]]; then
  [[ "$(ip_kind "$v6")" == 6net ]] || { echo "ERROR: '$v6' is not an IPv6 network (e.g. 2a01:4f8:1:2::/64)" >&2; exit 1; }
  set_config SERVER_IPV6_NET "$v6"
fi
if grep -q '^SERVER_IPV4=.' "$CONFIG" 2>/dev/null; then
  grep -E '^SERVER_IPV(4|6_NET)=' "$CONFIG" | sed 's/^/    /'
else
  echo "    WARNING: SERVER_IPV4 not set — the agent will REFUSE every unlock until it is."
  echo "    After the first terraform apply, re-run with MENEGROTH_SERVER_IPV4=... (and"
  echo "    MENEGROTH_SERVER_IPV6_NET=...) exported, or edit $CONFIG."
fi

op_sa() { # run op as the service account
  OP_SERVICE_ACCOUNT_TOKEN="$(cat "$TOKEN_FILE")" "$OP" "$@"
}

echo "==> Verifying service-account access to the '$OP_VAULT' vault"
op_sa vault get "$OP_VAULT" >/dev/null

# The unlock SSH key is generated BY 1Password (never exists locally at
# rest); only its public half leaves the vault. Items are created by
# scripts/bootstrap/10-onepassword.sh under the menegroth-bootstrap SA —
# this read-only account cannot (and should not) create them.
if ! op_sa item get unlock-ssh-key --vault "$OP_VAULT" >/dev/null 2>&1; then
  echo "ERROR: item 'unlock-ssh-key' not found in '$OP_VAULT'." >&2
  echo "  Run the bootstrap phase that creates the vault items first:" >&2
  echo "    MENEGROTH_OP_BOOTSTRAP_TOKEN=... scripts/bootstrap/bootstrap.sh 10-onepassword" >&2
  echo "  …then re-run this installer." >&2
  exit 1
fi

echo "==> Unlock key public half (bootstrap stores it at Infisical /unlock/MAC_UNLOCK_SSH_PUBKEY for the image build):"
op_sa item get unlock-ssh-key --vault "$OP_VAULT" --fields "public key"

echo "==> Self-check: reading all unlock secrets via the service account"
for ref in \
  "op://${OP_VAULT}/luks-passphrase/password" \
  "op://${OP_VAULT}/unlock-ssh-key/private key?ssh-format=openssh" \
  "op://${OP_VAULT}/ntfy/url"; do
  if op_sa read "$ref" >/dev/null 2>&1; then
    echo "    OK   $ref"
  else
    echo "    FAIL $ref — create the item in the 1Password app (vault: $OP_VAULT)" >&2
    SELF_CHECK_FAILED=1
  fi
done
[[ -z "${SELF_CHECK_FAILED:-}" ]] || exit 1

echo "==> Caching the ntfy URL (0600) for alerts when 1Password is unreachable"
(umask 077 && op_sa read "op://${OP_VAULT}/ntfy/url" > "${HOME}/.config/menegroth-server-unlock/ntfy-url")

echo "==> Installing launchd agent"
sed "s|__HOME__|${HOME}|g" com.menegroth-server.unlock.plist > "$PLIST_DEST"
launchctl bootout "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST"

echo "==> Done. The agent polls every 30 s while this Mac is awake."
echo "    Logs: ~/.local/state/menegroth-server-unlock/agent.log"
echo "    Check what it sees: ~/.local/bin/menegroth-server-unlock --diagnose"
