#!/bin/bash
# Install the AI server unlock agent on this Mac. Idempotent; re-run after
# editing ai-server-unlock.sh to update the installed copy.
#
# All secrets live in 1Password (dedicated vault, service-account read-only
# access). The only credential this installer writes to disk is the
# service-account token (0600, FileVault at rest) — on disk so the agent
# keeps working across Mac reboots without re-running this installer.
set -euo pipefail
cd "$(dirname "$0")"

BIN="${HOME}/.local/bin/ai-server-unlock"
PLIST_DEST="${HOME}/Library/LaunchAgents/com.ai-server.unlock.plist"
TOKEN_FILE="${HOME}/.config/ai-server-unlock/op-token"
OP_VAULT="Menegroth"

OP="$(command -v op || true)"
[[ -z "$OP" && -x /opt/homebrew/bin/op ]] && OP=/opt/homebrew/bin/op
[[ -z "$OP" && -x /usr/local/bin/op ]] && OP=/usr/local/bin/op
if [[ -z "$OP" ]]; then
  echo "ERROR: 1Password CLI not found — install with: brew install 1password-cli" >&2
  exit 1
fi

echo "==> Installing unlock script to $BIN"
mkdir -p "${HOME}/.local/bin" "${HOME}/.local/state/ai-server-unlock" \
  "${HOME}/.config/ai-server-unlock"
install -m 0700 ai-server-unlock.sh "$BIN"

if [[ ! -f "$TOKEN_FILE" ]]; then
  echo "==> Storing the menegroth-unlock service-account token (0600)"
  if [[ -n "${MENEGROTH_OP_UNLOCK_TOKEN:-}" ]]; then
    OP_TOKEN="$MENEGROTH_OP_UNLOCK_TOKEN"
    echo "    Using \$MENEGROTH_OP_UNLOCK_TOKEN from the environment."
  else
    echo "    This is the READ-ONLY service account scoped to the '$OP_VAULT'"
    echo "    vault only (README seed steps). Paste its token (it will not echo):"
    read -rs OP_TOKEN
    echo
  fi
  umask 177
  printf '%s\n' "$OP_TOKEN" > "$TOKEN_FILE"
  umask 022
  unset OP_TOKEN
fi

op_sa() { # run op as the service account
  OP_SERVICE_ACCOUNT_TOKEN="$(cat "$TOKEN_FILE")" "$OP" "$@"
}

echo "==> Verifying service-account access to the '$OP_VAULT' vault"
op_sa vault get "$OP_VAULT" >/dev/null

# The unlock SSH key is generated BY 1Password (never exists locally at
# rest); only its public half leaves the vault. Items are created by
# scripts/bootstrap/10-onepassword.sh under the menegroth-bootstrap SA —
# this read-only account cannot (and should not) create them.
if ! op_sa item get unlock-ssh-key --vault "$OP_VAULT" >/dev/null 2>&1; then
  echo "ERROR: item 'unlock-ssh-key' not found in '$OP_VAULT'." >&2
  echo "  Run the bootstrap phase that creates the vault items first:" >&2
  echo "    MENEGROTH_OP_BOOTSTRAP_TOKEN=... scripts/bootstrap/bootstrap.sh 10-onepassword" >&2
  echo "  …then re-run this installer." >&2
  exit 1
fi

echo "==> Unlock key public half (put into packer/fde-image.pkr.hcl -> mac_unlock_ssh_pubkey):"
op_sa item get unlock-ssh-key --vault "$OP_VAULT" --fields "public key"

echo "==> Self-check: reading all unlock secrets via the service account"
for ref in \
  "op://${OP_VAULT}/luks-passphrase/password" \
  "op://${OP_VAULT}/unlock-ssh-key/private key?ssh-format=openssh" \
  "op://${OP_VAULT}/ntfy/url"; do
  if op_sa read "$ref" >/dev/null 2>&1; then
    echo "    OK   $ref"
  else
    echo "    FAIL $ref — create the item in the 1Password app (vault: $OP_VAULT)" >&2
    SELF_CHECK_FAILED=1
  fi
done
[[ -z "${SELF_CHECK_FAILED:-}" ]] || exit 1

echo "==> Installing launchd agent"
sed "s|__HOME__|${HOME}|g" com.ai-server.unlock.plist > "$PLIST_DEST"
launchctl bootout "gui/$(id -u)" "$PLIST_DEST" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_DEST"

echo "==> Done. The agent polls every 30 s while this Mac is awake."
echo "    Logs: ~/.local/state/ai-server-unlock/agent.log"
